os: windows
language: shell
python:
- "3.9"

install:
- python -m pip install --upgrade pip
- python -m pip install flake8
- python -m pip install -r requirements.txt
- python -m pip install .

script:
- python -m flake8 --ignore=E,F403,F405,W503,W504 .
- python test.py
