environment:
  matrix:
    - PYTHON: "C:\\Python39"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 32
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: 3.9
      PYTHON_ARCH: 64

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install flake8
  - python -m pip install -r requirements.txt
  - python -m pip install .

build: false

test_script:
  - python -m flake8 --ignore=E,F403,F405,W503,W504 .
  - python test.py
